### ISSUE TITLE
Cannot import profile (SimHub V9.1.31)

### ISSUE THREAD

**Issue by stssamsts** [MorGuux/SwitchableProperties#2]
Hi and first of all, HUGE thanks for this perfect plugin

I cannot add (import button) profile now on SH V9.1.31)
EDIT: New SH major update is out 9.2.0

Can you plan to update the plugin please

Huge thanks again
Take care,
Sam

**Comment by MorGuux** [comment]
Hi Sam,

Just tested import and export in 9.2.0, all working fine. Can you give me a sample .json to import so I can replicate the issue.

Cheers,
Morgan

**Comment by stssamsts** [comment]
Hi Morgan, it's not a problem with *.json import, it's when I click to "Import" button on the SwitchableProperties page (SimHub > SwitchableProperties tab) I don't have any dialogbox for import any file, export working OK.

I've also deleted the DLL, run SimHub, close SimHub then downloaded SwitchableProperties.dll again and placed in SimHub folder, run SimHub and enable plug-in when asked (and checked the menu side) but I cannot click on Import (nothing happen)

Huge thanks for your help !!!

**Comment by MorGuux** [comment]
Can you send me your simhub log file? Import window opens fine for me so there's something amiss between your install and mine :)

**Comment by stssamsts** [comment]
> Can you send me your simhub log file? Import window opens fine for me so there's something amiss between your install and mine :)

Yes mate there it is 👍 
[SimHub.txt](https://github.com/MorGuux/SwitchableProperties/files/14377335/SimHub.txt)

**Comment by MorGuux** [comment]
Okay I see the error in the log, I'll get on a fix for it (once I can re-produce it lol)

**Comment by MorGuux** [comment]
Pushed a new release (all it needed was a re-compile targeting the new SimHub UI libraries), enjoy!

https://github.com/MorGuux/SwitchableProperties/releases/tag/v1.8

**Comment by stssamsts** [comment]
Outch ! Now I've this error after using new DLL:

![image](https://github.com/MorGuux/SwitchableProperties/assets/18287052/5d03f2de-6def-4103-b593-9214347a5112)

`06:55:03.957 ERROR An error occured while loading plugin settings control for SwitchableProperties: System.Exception: The component 'SwitchableProperties.SettingsControl' does not have a resource identified by the URI '/SwitchableProperties;component/settingscontrol.xaml'.
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SwitchableProperties.SettingsControl.InitializeComponent()
   at SwitchableProperties.SettingsControl..ctor(SwitchablePropertiesPlugin plugin)
   at SwitchableProperties.SwitchablePropertiesPlugin.GetWPFSettingsControl(PluginManager pluginManager)
   at SimHub.Plugins.IWPFSettingsExtensions.GetWidthLimitedWPFSettingsControl(IWPFSettings iWPFSettings, PluginManager pluginManager)
   at SimHubWPF.MainWindow.<>c__DisplayClass47_0.<LoadPluginsControls>b__0()`
